### ISSUE TITLE
STDP depresses cortico - cortical connections in a "minimal" three neurons Thalamo - Cortical model

### ISSUE THREAD

**Issue by leoneurocomp** [golosio/NeuronGPU#1]
I considered a simple 3 neurons system to mimic thalamus —> cortex   and   cortex <—> cortex interactions:

Axon delay : t_a = 1.5
Dendritic delay : t_d = 0.5
dt_stdp_update = t_post + t_d - (t_pre + t_a) = ∆t

**Network:**

"aeif" neurons

- TH : Thalamic neuron 
- CX1 : Cortex neuron 1
- CX2 : Cortex neuron 2
- SG : 3 spike generators 

**Connections:**

TH   —>   CX1  ,  CX2
CX1   <—>   CX2
SG0   —>   TH 
SG1   —>   CX1
SG2   —>   CX2

**Parameters:**

W_th_cx_0 = 100.
Wmax_th_cx = 105.
lambda_th = 0.03

W_cx_cx_0 = 0.01
Wmax_cx_cx = 150.
lambda_cx = 0.1

Spike generators are set to make the network firing at times:

TH Spike Times = [100.5 , 200.5 , 300.5 , 400.5] ms
CX1 Spike Times = [102.5 , 202.5 , 302.5 , 402.5] ms
CX2 Spike Times = [104.5 , 204.5 , 304.5 , 404.5] ms

Since t_d - t_a = -1 ms every 100 ms (we neglect 100 ms ISI):
1) TH  —> CX1 : ∆t = 2ms -1ms > 0  connection should POTENTIATE   (OK)
2) TH  —> CX2 : ∆t = 4ms -1ms > 0  connection should POTENTIATE  (OK)
3) CX1  —> CX2 : ∆t = 2ms -1ms > 0  connection should POTENTIATE  (connection get depressed)
4) CX2  —> CX1 : ∆t = -2ms -1ms < 0  connection should WEAKEN (updates correctly negatives ∆t but neglects potentiations (∆t=97. ms))

although thalamo - cortical connections are potentiated correctly, cortico-cortical connections are bidirectionally depressed making it impossible to form pairs of coupled neurons

I attach a zip with code and output of this system " issue_case_1.py
and the code to run the same model with only CX firing "issue_case_2.py"
[Issue_3neurons_NGPU.zip](https://github.com/golosio/NeuronGPU/files/5394632/Issue_3neurons_NGPU.zip)

**Comment by golosio** [comment]
Should be fixed with commits https://github.com/golosio/NeuronGPU/commit/c7e24c5cb15b51feacf5509502f6e04a520c246e
and https://github.com/golosio/NeuronGPU/commit/9fc5fb3fe0a26c3fe65d97447b8843812b903e7d
