### ISSUE TITLE
Is there anything like nest.ResetNetwork?

### ISSUE THREAD

**Issue by HilbertHuangHitomi** [golosio/NeuronGPU#3]
I would like to run the simulation under different conditions automatically with a loop. It looks like this :
> for i in range(times):
>      net = Network(sim_dict, net_dict, stim_dict)
>      net.create()
>      net.connect()
>      net.simulate(sim_dict['t_sim'])
>      SaveData()

However, when a simulation is completed, the next one would be stuck at `net.create() `, as `ValueError: Nodes cannot be created after calibration`.
I think we need a reset operation like `nest.ResetNetwork` to initialize the network before we start to create it again, but I could not find it. Is there anything like this, please?

**Comment by golosio** [comment]
Unfortunately currently there is no reset function in NeuronGPU. As a possible workaround, if you are working in bash you can run an external bash script that launches the python script several times. If you need the loop step index, you can use a template python script and a substitution, as in the following example:
file ```prova.sh```:
```
 #!/bin/bash
for i in $(seq 1 10); do
    cat prova_templ.py | sed "s/__i__/$i/" > prova.py
    python prova.py
done
```
file ```prova_templ.py```:
```
run_index = __i__
print("Running step n. ", run_index)
```
To execute it, type:
```. prova.sh```
Let me know if this kind of solution is suitable for your needs.

**Comment by HilbertHuangHitomi** [comment]
Thank you for the response!
It works, but harder to maintain since it needs interactions between bash and python.
I found another solution, using the `subprocess` package. For example, in file `main.py`
> for i in range(times):
> subprocess.run(['python run_simulation.py'])

Then we can run the whole process by `python main.py`. It may be easier to use.

BTW, is NeuronGPU still actively developed? It is friendly to use for those who are familiar with nest and python. I think this is one important advantage above GeNN. I do look forward to more improvement :P

**Comment by golosio** [comment]
Thank you for the interesting and useful solution!
Sure, it is actively developed. If you publish something using it, please cite:
https://www.frontiersin.org/articles/10.3389/fncom.2021.627620/full
Best, Bruno

**Comment by HilbertHuangHitomi** [comment]
Thank you very much !
