### ISSUE TITLE
MPI_Isend or MPI_Send?May be loss data?

### ISSUE THREAD

**Issue by iniwap** [golosio/NeuronGPU#5]
In neurongpu.cu(Line 524 & 528) & spike_mpi.cu(320 & 351)，If use "MPI_Isend" & "MPI_Irecv"(Not blocking)，may be not recv data(lose data)?Is that right?

**Comment by golosio** [comment]
Thank you for pointing this out. The use of nonblocking MPI send/recv is done on purpose using an algorithm that should guarantee parallel exchange of spikes among MPI processes without any data loss. However, there was a bug in a previous implementation of this algorithm, a missing MPI_Barrier. We fixed the bug but I forgot to commit the fix until now. Sorry, but I did not think that someone could start to use the MPI feature of NeuronGPU before it was documented. Anyway now I committed the fix, and I also prepared a new release. We tested the MPI functions of NeuronGPU on very large networks (up to 24 billion connections on 32 cluster nodes) and we did not observe any data loss. Please try to update your NeuronGPU version and let me know if you still encounter problems.

**Comment by iniwap** [comment]
Suppose A->MPI_Isend ，B->MPI_Irecv，if B->MPI_Irecv calling before A->MPI_Isend(both not blocking，different machines have difficulty guaranteeing the calling order , even if there is synchronization before)， Does this situation not lose data?Although the probability of this situation is relatively low.

**Comment by golosio** [comment]
This is not a NeuronGPU issue, is a MPI programming question, suitable for a programming forum or for a question/answer website, as for instance stackoverflow. Clearly MPI nonblocking send/recv work well without any data loss if they are used properly, it is not matter of low probability, just using them in a proper way, but this is not the right place for this discussion. Please limit issue reporting usage to specific problems, and clearly identify the specific problems in the title. Isolate the problem, create a reduced test case and a live example, A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.
